SOFTWARE-5963: Document Kuantifier
osg-htc/docs pull request #194
Opened 2024-08-19 15:09 UTC by mwestphall

- Document installing helm, using helm to install prometheus, kube-state-metrics, and kuantifier
- Document known constraints for kuantifier accounting
  - single-container pods, jobs run via Jobs rather than deployments, mandatory CPU request
- Document required changes to values.yaml for configuring kuantifier for gratia output

2025-03-25 18:23 UTC, mwestphall commented
@brianhlin @matyasselmeci looks like we never got this very old PR reviewed, any comments on it?

2025-03-25 21:21 UTC, brianhlin requested changes
Oops, I had a half-finished review here. Mostly LGTM, mostly nitpicks in-line

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +      to determine processor count for GRACC reporting. Ensure a cpu request is set for pods in
```suggestion
      to determine processor count for GRACC reporting. Ensure a CPU request is set for pods in
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +1. Ensure that the namespace where your workload pods run is properly configured.
I'm a little nervous about being prescriptive about installation method here: I don't really want to be on the hook for supporting Prometheus/kube-state-metrics installs directly. I think it's fine if we have light recs on installation methods like you do above, maybe elaborating that the `prometheus-community` provides Helm charts for both

Also, if we remove the first two list items, a single enumerated item looks odd so we can get rid of the enumeration.

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +Kuantifier itself is also installed via a helm chart, hosted at hub.opensciencegrid.org/iris-hep/kuantifier.
```suggestion
Kuantifier itself is also installed via a Helm chart, hosted on [OSG Harbor](https://hub.opensciencegrid.org)
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +[helm chart README on Github](helm-values-readme).
```suggestion
[Helm chart README on Github](helm-values-readme).
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +1. Fetch the default values.yaml for kuantifier. This file can be obtained in several ways.
```suggestion
1. Fetch the default values.yaml for Kuantifier. This file can be obtained in several ways.
```

I would just pick one way here and I think I lean towards the CLI

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +        - `PROMETHEUS_SERVER`: The DNS name of the prometheus server installed in your kubernetes cluster.
```suggestion
        - `PROMETHEUS_SERVER`: The DNS name of the Prometheus server installed in your Kubernetes cluster. 
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +            - If Prometheus was installed in your cluster via the prometheus community helm chart in the monitoring
```suggestion
            - If Prometheus was installed in your cluster via the prometheus-community Helm chart in the monitoring
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +After running helm install, ensure that the expected kubernetes objects have been created. The following commands assume
```suggestion
After running `helm install`, ensure that the expected Kubernetes objects have been created. The following commands assume
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +that kuantifier has been installed in the monitoring namespace.
```suggestion
that Kuantifier has been installed in the monitoring namespace.
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +1. Check that a CronJob was created for running the kuantifier processor:
```suggestion
1. Check that a CronJob was created for running the Kuantifier processor:
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +If the helm chart artifacts are present as expected, run a test instance of the CronJob and inspect its output.
```suggestion
If the Helm chart artifacts are present as expected, run a test instance of the CronJob and inspect its output.
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +1. Inspect the logs from the processor initContainer, which queries prometheus to generate output records.
```suggestion
1. Inspect the logs from the processor initContainer, which queries Prometheus to generate output records.
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +1. Inspect the logs from the gratia-output container, which sends the output records to GRACC.
```suggestion
1. Inspect the logs from the `gratia-output` container, which sends the output records to GRACC.
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +If both the processor initContainer and gratia-output container run to completion without error, the next step
```suggestion
If both the processor initContainer and `gratia-output` container run to completion without error, the next step
```

2025-03-25 21:21 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +is to confirm with a member of the OSG technology team that the results are visible in GRACC.
I think we should just point them at the https://gracc.opensciencegrid.org/d/000000079/site-summary?orgId=1&var-site=Purdue%20Geddes&var-type=Batch&var-interval=$__auto_interval_interval dashboard and have them self service this. It may take a few hours for results to show up (Ashton/Derek would know for sure)

That being said, there are lots of places where this documentation can go wrong. Please add our standard `Getting Help` section

2025-05-29 21:12 UTC, mwestphall commented
@brianhlin I've updated the docs to call out a few OpenShift-specific configuration considerations, let me know if you'd like to see more details.

2025-05-30 21:27 UTC, brianhlin commented on docs/other/monitor-kubernetes-kuantifier.md
> +            Ensure that the release tag for values.yaml in the git repo corresponds to the version of the chart you're installing.
I wouldn't even give the second one as an option

2025-05-30 22:11 UTC, mwestphall commented on docs/other/monitor-kubernetes-kuantifier.md
> +against that cluster.
Yeah, I'll update the text to reflect that.

2025-05-30 22:17 UTC, merged